sudo: false
language: python
python:
  - "2.7.13"
  - "2.7.14"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

ache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - LC_ALL=en_US.UTF-8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - george-edison55-precise-backports
    packages:
    - build-essential
    - autoconf
    - cmake
    - cmake-data

install:
  - |
    PYTHONPATH=.:$PYTHONPATH
    make

script:
  - |
    make test
